server:
  port: 8085
spring:
  application:
    name: eureka-advise-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8086/eureka}"
